name: Build Deploy
on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: aws credential
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: checkout branch
      uses: actions/checkout@v2

    - name: build package
      run: GOOS=linux go build

    - name: zip local package for lambda
      run: zip function.zip site_update_checker

    - name: check function
      id: check-function
      continue-on-error: true
      run: >
        aws lambda get-function
        --function-name site_update_checker

    - name: create function
      id: create-function
      if: steps.check-function.outcome == 'failure'
      run: >
        aws lambda create-function
        --function-name site_update_checker
        --zip-file fileb://artifact.zip
        --handler lambda_function.lambda_handler
        --runtime go1.x
        --role ${{ secrets.AWS_ARN_ROLE }}
        --timeout 10

    - name: update function
      if: steps.create-function.conclusion == 'skipped'
      run: >
        aws lambda update-function-code
        --function-name site_update_checker
        --zip-file fileb://artifact.zip
